/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fod_example_EffectUtils */

#ifndef _Included_com_fod_example_EffectUtils
#define _Included_com_fod_example_EffectUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_fod_example_EffectUtils_MODE_NORMAL
#define com_fod_example_EffectUtils_MODE_NORMAL 0L
#undef com_fod_example_EffectUtils_MODE_LUOLI
#define com_fod_example_EffectUtils_MODE_LUOLI 1L
#undef com_fod_example_EffectUtils_MODE_DASHU
#define com_fod_example_EffectUtils_MODE_DASHU 2L
#undef com_fod_example_EffectUtils_MODE_JINGSONG
#define com_fod_example_EffectUtils_MODE_JINGSONG 3L
#undef com_fod_example_EffectUtils_MODE_GAOGUAI
#define com_fod_example_EffectUtils_MODE_GAOGUAI 4L
#undef com_fod_example_EffectUtils_MODE_KONGLING
#define com_fod_example_EffectUtils_MODE_KONGLING 5L
/*
 * Class:     com_fod_example_EffectUtils
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_fod_example_EffectUtils_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
